image:
  repository: tccr.io/truecharts/qbittorrent
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:0f75c164b7a4c23cf4d0b925af142254871483b2c1525f3c79b2c873898d601b

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
  torrentudp:
    enabled: true
    ports:
      torrentudp:
        enabled: true
        port: 6881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"

additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: "/config/custom-cont-init.d"
    name: qbittorrent-scripts

portal:
  enabled: true
